package com.websitename.dao;

import com.websitename.entities.Activities;
 
/**
 * DAO interface for table: Activities.
 * @author autogenerated
 */
public interface ActivitiesDao extends GenericDAO<Activities,  String>  {
	// constructor only
}

