package com.websitename.dao;

import java.util.List;

import com.websitename.entities.Friend;
 
/**
 * DAO interface for table: Friend.
 * @author autogenerated
 */
public interface FriendDao extends GenericDAO<Friend,  String>  {

	List<Friend> getByCriteria(Friend friend) throws Exception;
	// constructor only
}
