package com.websitename.dao;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.criterion.Restrictions;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.websitename.entities.Itinerary;
import com.websitename.entities.User;
import com.websitename.utils.Utils;
 
/**
 * DAO interface for table: Itinerary.
 * @author autogenerated
 */
public interface ItineraryDao extends GenericDAO<Itinerary,  String>  {
	// constructor only

	public List<Itinerary> getItineraryForDate(String id, String formatDate) throws Exception;

	public List<Itinerary> getByCriteria(Itinerary it) throws Exception;
}

