package com.websitename.dao;

import com.websitename.entities.Location;
 
/**
 * DAO interface for table: Location.
 * @author autogenerated
 */
public interface LocationDao extends GenericDAO<Location,  String>  {
	// constructor only
}

