package com.websitename.dao;

import com.websitename.entities.Plan;
 
/**
 * DAO interface for table: Plan.
 * @author autogenerated
 */
public interface PlanDao extends GenericDAO<Plan,  String>  {
	// constructor only
}

