package com.websitename.entities;

import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.proxy.HibernateProxy;

import com.websitename.entities.iface.IItinerary;


/** 
 * Object mapping for hibernate-handled table: itinerary.
 * @author autogenerated
 */

@Entity
@Table(name = "itinerary", catalog = "websitename")
public class Itinerary implements Cloneable, Serializable, IItinerary {

	/** Serial Version UID. */
	private static final long serialVersionUID = -558970239L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, String> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, String>());
	
	/** hashCode temporary storage. */
	private volatile String hashCode;
	

	/** Field mapping. */
	private String date;
	/** Field mapping. */
	private String id;
	/** Field mapping. */
	private Location location;
	/** Field mapping. */
	private Plan plan;
	/** Field mapping. */
	private Integer sequence;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Itinerary() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Itinerary(String id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param date String object;
	 * @param id String object;
	 * @param location Location object;
	 * @param plan Plan object;
	 * @param sequence Integer object;
	 */
	public Itinerary(String date, String id, Location location, 					
			Plan plan, Integer sequence) {

		this.date = date;
		this.id = id;
		this.location = location;
		this.plan = plan;
		this.sequence = sequence;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Itinerary.class;
	}
 

    /**
     * Return the value associated with the column: date.
	 * @return A String object (this.date)
	 */
	@Column( nullable = false, length = 36  )
	public String getDate() {
		return this.date;
		
	}
	

  
    /**  
     * Set the value related to the column: date.
	 * @param date the date value you wish to set
	 */
	public void setDate(final String date) {
		this.date = date;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
    @Id 
	@Column( name = "id", nullable = false, length = 36  )
	public String getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final String id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: location.
	 * @return A Location object (this.location)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.EAGER )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "location_id", nullable = false )
	public Location getLocation() {
		return this.location;
		
	}
	

  
    /**  
     * Set the value related to the column: location.
	 * @param location the location value you wish to set
	 */
	public void setLocation(final Location location) {
		this.location = location;
	}

    /**
     * Return the value associated with the column: plan.
	 * @return A Plan object (this.plan)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "plan_id", nullable = false )
	public Plan getPlan() {
		return this.plan;
		
	}
	

  
    /**  
     * Set the value related to the column: plan.
	 * @param plan the plan value you wish to set
	 */
	public void setPlan(final Plan plan) {
		this.plan = plan;
	}

    /**
     * Return the value associated with the column: sequence.
	 * @return A Integer object (this.sequence)
	 */
	@Column( nullable = false  )
	public Integer getSequence() {
		return this.sequence;
		
	}
	

  
    /**  
     * Set the value related to the column: sequence.
	 * @param sequence the sequence value you wish to set
	 */
	public void setSequence(final Integer sequence) {
		this.sequence = sequence;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Itinerary clone() throws CloneNotSupportedException {
		
        final Itinerary copy = (Itinerary)super.clone();

		copy.setDate(this.getDate());
		copy.setId(this.getId());
		copy.setLocation(this.getLocation());
		copy.setPlan(this.getPlan());
		copy.setSequence(this.getSequence());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("date: " + this.getDate() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("sequence: " + this.getSequence());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Itinerary that; 
		try {
			that = (Itinerary) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getDate() == null) && (that.getDate() == null)) || (getDate() != null && getDate().equals(that.getDate())));
		result = result && (((getLocation() == null) && (that.getLocation() == null)) || (getLocation() != null && getLocation().getId().equals(that.getLocation().getId())));	
		result = result && (((getPlan() == null) && (that.getPlan() == null)) || (getPlan() != null && getPlan().getId().equals(that.getPlan().getId())));	
		result = result && (((getSequence() == null) && (that.getSequence() == null)) || (getSequence() != null && getSequence().equals(that.getSequence())));
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					String newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null ) {
							newHashCode = getId();
						} else {
						newHashCode = String.valueOf(super.hashCode());

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode.hashCode();
	}
	

	
}
