package com.websitename.entities.iface;


/** 
 * Object interface mapping for hibernate-handled table: activities.
 * @author autogenerated
 */

public interface IActivities {



    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

    /**
     * Return the value associated with the column: value.
	 * @return A String object (this.value)
	 */
	String getValue();
	

  
    /**  
     * Set the value related to the column: value.
	 * @param value the value value you wish to set
	 */
	void setValue(final String value);

	// end of interface
}