package com.websitename.entities.iface;
import com.websitename.entities.User;


/** 
 * Object interface mapping for hibernate-handled table: friend.
 * @author autogenerated
 */

public interface IFriend {



    /**
     * Return the value associated with the column: friendUser.
	 * @return A User object (this.friendUser)
	 */
	User getFriendUser();
	

  
    /**  
     * Set the value related to the column: friendUser.
	 * @param friendUser the friendUser value you wish to set
	 */
	void setFriendUser(final User friendUser);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: user.
	 * @return A User object (this.user)
	 */
	User getUser();
	

  
    /**  
     * Set the value related to the column: user.
	 * @param user the user value you wish to set
	 */
	void setUser(final User user);

	// end of interface
}