package com.websitename.entities.iface;
import com.websitename.entities.Location;
import com.websitename.entities.Plan;


/** 
 * Object interface mapping for hibernate-handled table: itinerary.
 * @author autogenerated
 */

public interface IItinerary {



    /**
     * Return the value associated with the column: date.
	 * @return A String object (this.date)
	 */
	String getDate();
	

  
    /**  
     * Set the value related to the column: date.
	 * @param date the date value you wish to set
	 */
	void setDate(final String date);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: location.
	 * @return A Location object (this.location)
	 */
	Location getLocation();
	

  
    /**  
     * Set the value related to the column: location.
	 * @param location the location value you wish to set
	 */
	void setLocation(final Location location);

    /**
     * Return the value associated with the column: plan.
	 * @return A Plan object (this.plan)
	 */
	Plan getPlan();
	

  
    /**  
     * Set the value related to the column: plan.
	 * @param plan the plan value you wish to set
	 */
	void setPlan(final Plan plan);

    /**
     * Return the value associated with the column: sequence.
	 * @return A Integer object (this.sequence)
	 */
	Integer getSequence();
	

  
    /**  
     * Set the value related to the column: sequence.
	 * @param sequence the sequence value you wish to set
	 */
	void setSequence(final Integer sequence);

	// end of interface
}