package com.websitename.entities.iface;
import java.util.Date;
import java.util.Set;

import com.websitename.entities.Itinerary;
import com.websitename.entities.PlanMembers;


/** 
 * Object interface mapping for hibernate-handled table: plan.
 * @author autogenerated
 */

public interface IPlan {



	  /**
     * Return the value associated with the column: latitude.
	 * @return A Double object (this.latitude)
	 */
	Double getLatitude();
	

  
    /**  
     * Set the value related to the column: latitude.
	 * @param latitude the latitude value you wish to set
	 */
	void setLatitude(final Double latitude);
	
	
	  /**
     * Return the value associated with the column: longitude.
	 * @return A Double object (this.longitude)
	 */
	Double getLongitude();
	

  
    /**  
     * Set the value related to the column: longitude.
	 * @param longitude the longitude value you wish to set
	 */
	void setLongitude(final Double longitude);
	
	
	
    /**
     * Return the value associated with the column: endDate.
	 * @return A Date object (this.endDate)
	 */
	String getEndDate();
	

  
    /**  
     * Set the value related to the column: endDate.
	 * @param endDate the endDate value you wish to set
	 */
	void setEndDate(final String endDate);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: itinerary.
	 * @return A Set&lt;Itinerary&gt; object (this.itinerary)
	 */
	Set<Itinerary> getItineraries();
	
	/**
	 * Adds a bi-directional link of type Itinerary to the itineraries set.
	 * @param itinerary item to add
	 */
	void addItinerary(Itinerary itinerary);

  
    /**  
     * Set the value related to the column: itinerary.
	 * @param itinerary the itinerary value you wish to set
	 */
	void setItineraries(final Set<Itinerary> itinerary);

    /**
     * Return the value associated with the column: location.
	 * @return A String object (this.location)
	 */
	String getLocation();
	

  
    /**  
     * Set the value related to the column: location.
	 * @param location the location value you wish to set
	 */
	void setLocation(final String location);

    /**
     * Return the value associated with the column: planMembers.
	 * @return A Set&lt;PlanMembers&gt; object (this.planMembers)
	 */
	Set<PlanMembers> getPlanMemberss();
	
	/**
	 * Adds a bi-directional link of type PlanMembers to the planMemberss set.
	 * @param planMembers item to add
	 */
	void addPlanMembers(PlanMembers planMembers);

  
    /**  
     * Set the value related to the column: planMembers.
	 * @param planMembers the planMembers value you wish to set
	 */
	void setPlanMemberss(final Set<PlanMembers> planMembers);

    /**
     * Return the value associated with the column: startDate.
	 * @return A Date object (this.startDate)
	 */
	String getStartDate();
	

  
    /**  
     * Set the value related to the column: startDate.
	 * @param startDate the startDate value you wish to set
	 */
	void setStartDate(final String startDate);

	// end of interface
}