package com.websitename.entities.iface;
import com.websitename.entities.Plan;
import com.websitename.entities.User;


/** 
 * Object interface mapping for hibernate-handled table: plan_members.
 * @author autogenerated
 */

public interface IPlanMembers {


    /**
     * Return the value associated with the column: iscreator.
	 * @return A Boolean object (this.iscreator)
	 */
	Boolean isIscreator();
	

  
    /**  
     * Set the value related to the column: iscreator.
	 * @param iscreator the iscreator value you wish to set
	 */
	void setIscreator(final Boolean iscreator);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: plan.
	 * @return A Plan object (this.plan)
	 */
	Plan getPlan();
	

  
    /**  
     * Set the value related to the column: plan.
	 * @param plan the plan value you wish to set
	 */
	void setPlan(final Plan plan);

    /**
     * Return the value associated with the column: user.
	 * @return A User object (this.user)
	 */
	User getUser();
	

  
    /**  
     * Set the value related to the column: user.
	 * @param user the user value you wish to set
	 */
	void setUser(final User user);

	// end of interface
}