package com.websitename.entities.iface;
import java.util.Set;

import com.websitename.entities.Friend;
import com.websitename.entities.PlanMembers;


/** 
 * Object interface mapping for hibernate-handled table: user.
 * @author autogenerated
 */

public interface IUser {



    /**
     * Return the value associated with the column: email.
	 * @return A String object (this.email)
	 */
	String getEmail();
	

  
    /**  
     * Set the value related to the column: email.
	 * @param email the email value you wish to set
	 */
	void setEmail(final String email);

    /**
     * Return the value associated with the column: firstName.
	 * @return A String object (this.firstName)
	 */
	String getFirstName();
	

  
    /**  
     * Set the value related to the column: firstName.
	 * @param firstName the firstName value you wish to set
	 */
	void setFirstName(final String firstName);

    /**
     * Return the value associated with the column: friend.
	 * @return A Set&lt;Friend&gt; object (this.friend)
	 */
	Set<Friend> getFriends();
	
	/**
	 * Adds a bi-directional link of type Friend to the friends set.
	 * @param friend item to add
	 */
	void addFriend(Friend friend);

  
    /**  
     * Set the value related to the column: friend.
	 * @param friend the friend value you wish to set
	 */
	void setFriends(final Set<Friend> friend);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: lastName.
	 * @return A String object (this.lastName)
	 */
	String getLastName();
	

  
    /**  
     * Set the value related to the column: lastName.
	 * @param lastName the lastName value you wish to set
	 */
	void setLastName(final String lastName);

    /**
     * Return the value associated with the column: password.
	 * @return A String object (this.password)
	 */
	String getPassword();
	

  
    /**  
     * Set the value related to the column: password.
	 * @param password the password value you wish to set
	 */
	void setPassword(final String password);

    /**
     * Return the value associated with the column: planMembers.
	 * @return A Set&lt;PlanMembers&gt; object (this.planMembers)
	 */
	Set<PlanMembers> getPlanMemberss();
	
	/**
	 * Adds a bi-directional link of type PlanMembers to the planMemberss set.
	 * @param planMembers item to add
	 */
	void addPlanMembers(PlanMembers planMembers);

  
    /**  
     * Set the value related to the column: planMembers.
	 * @param planMembers the planMembers value you wish to set
	 */
	void setPlanMemberss(final Set<PlanMembers> planMembers);

	// end of interface
}