package com.websitename.dao.impl;

import org.springframework.stereotype.Repository;

import com.websitename.dao.ActivitiesDao;
import com.websitename.entities.Activities;
 
 
/**
 * DAO for table: Activities.
 * @author autogenerated
 */
@Repository
public class ActivitiesDaoImpl extends GenericHibernateDaoImpl<Activities, String> implements ActivitiesDao {
	
	/** Constructor method. */
		public ActivitiesDaoImpl() {
			super(Activities.class);
		}
	}

