package com.websitename.dao.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.websitename.dao.FriendDao;
import com.websitename.entities.Friend;
import com.websitename.utils.Utils;


/**
 * DAO for table: Friend.
 * @author autogenerated
 */
@Repository
public class FriendDaoImpl extends GenericHibernateDaoImpl<Friend, String> implements FriendDao {

	/** Constructor method. */
	public FriendDaoImpl() {
		super(Friend.class);
	}

	@Override
	@Transactional(readOnly = true, propagation = Propagation.REQUIRED)
	public List<Friend> getByCriteria(Friend friend) throws Exception {
		try {
			Criteria crit = getSession().createCriteria(getPersistentClass());

			if(friend.getUser()!=null){
				crit.add(Restrictions.eq("user",friend.getUser()));
			}
			if(friend.getFriendUser()!=null){
				crit.add(Restrictions.eq("friendUser",friend.getFriendUser()));
			}
			crit.setResultTransformer(Criteria.DISTINCT_ROOT_ENTITY);
			return crit.list();

		} catch (HibernateException e) {
			throw e;
		}	

	}
}

