package com.websitename.dao.impl;

import org.springframework.stereotype.Repository;

import com.websitename.dao.PlanDao;
import com.websitename.entities.Plan;
 
 
/**
 * DAO for table: Plan.
 * @author autogenerated
 */
@Repository
public class PlanDaoImpl extends GenericHibernateDaoImpl<Plan, String> implements PlanDao {
	
	/** Constructor method. */
		public PlanDaoImpl() {
			super(Plan.class);
		}
	}

